import type { Book, BookCategory } from './types';

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Amazing Spider-Man #1',
    author: 'Stan Lee',
    category: 'Comic Books',
    price: 49.99,
    condition: 'new',
    description: 'The classic first issue of The Amazing Spider-Man. A must-have for collectors.',
    imageUrl: 'https://placehold.co/300x450.png',
    featured: true,
    popular: true,
    slug: 'amazing-spiderman-1',
    stock: 10,
    tags: ['marvel', 'superhero', 'first issue'],
    publisher: 'Marvel Comics',
    publishedDate: '1963-03-10',
  },
  {
    id: '2',
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    category: 'Harry Potter',
    price: 25.00,
    condition: 'used',
    description: 'The book that started it all. Join Harry as he discovers he is a wizard.',
    imageUrl: 'https://placehold.co/300x450.png',
    featured: true,
    popular: true,
    slug: 'harry-potter-sorcerers-stone',
    stock: 5,
    isbn: '978-0590353427',
    pages: 309,
    publisher: 'Scholastic',
  },
  {
    id: '3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    category: 'Novels',
    price: 15.99,
    condition: 'new',
    description: 'A powerful story addressing serious issues of racial injustice and moral growth.',
    imageUrl: 'https://placehold.co/300x450.png',
    featured: true,
    popular: true,
    slug: 'to-kill-a-mockingbird',
    stock: 15,
    tags: ['classic', 'literature', 'pulitzer prize'],
  },
  {
    id: '4',
    title: 'Batman: The Killing Joke',
    author: 'Alan Moore',
    category: 'Comic Books',
    price: 19.99,
    condition: 'used',
    description: 'A dark and influential Batman story exploring the Joker\'s origin.',
    imageUrl: 'https://placehold.co/300x450.png',
    popular: true,
    slug: 'batman-killing-joke',
    stock: 7,
    tags: ['dc comics', 'batman', 'joker', 'graphic novel'],
  },
  {
    id: '5',
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    category: 'Harry Potter',
    price: 22.50,
    condition: 'new',
    description: 'Harry\'s second year at Hogwarts is filled with new challenges and dark secrets.',
    imageUrl: 'https://placehold.co/300x450.png',
    slug: 'harry-potter-chamber-of-secrets',
    stock: 8,
  },
  {
    id: '6',
    title: '1984',
    author: 'George Orwell',
    category: 'Novels',
    price: 12.00,
    condition: 'used',
    description: 'A dystopian novel set in a totalitarian society, exploring themes of surveillance and control.',
    imageUrl: 'https://placehold.co/300x450.png',
    slug: '1984-george-orwell',
    stock: 20,
    tags: ['dystopian', 'classic', 'political fiction'],
  },
  {
    id: '7',
    title: 'Saga, Vol. 1',
    author: 'Brian K. Vaughan',
    category: 'Comic Books',
    price: 14.99,
    condition: 'new',
    description: 'An epic space opera/fantasy comic book series about a husband and wife from long-warring extraterrestrial races.',
    imageUrl: 'https://placehold.co/300x450.png',
    featured: false,
    slug: 'saga-vol-1',
    stock: 12,
    tags: ['image comics', 'sci-fi', 'fantasy', 'graphic novel'],
  },
  {
    id: '8',
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    category: 'Harry Potter',
    price: 28.00,
    condition: 'new',
    description: 'Harry\'s third year at Hogwarts introduces Sirius Black and dangerous Dementors.',
    imageUrl: 'https://placehold.co/300x450.png',
    featured: true,
    slug: 'harry-potter-prisoner-of-azkaban',
    stock: 3,
  },
  {
    id: '9',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Novels',
    price: 10.50,
    condition: 'used',
    description: 'A classic novel depicting the Roaring Twenties and the elusive American Dream.',
    imageUrl: 'https://placehold.co/300x450.png',
    popular: true,
    slug: 'the-great-gatsby',
    stock: 18,
    tags: ['classic', 'american literature', 'jazz age'],
  },
  {
    id: '10',
    title: 'Watchmen',
    author: 'Alan Moore',
    category: 'Comic Books',
    price: 24.99,
    condition: 'new',
    description: 'A groundbreaking graphic novel that deconstructs superhero archetypes.',
    imageUrl: 'https://placehold.co/300x450.png',
    slug: 'watchmen-alan-moore',
    stock: 9,
    tags: ['dc comics', 'graphic novel', 'deconstruction'],
  },
];

export const bookCategories: BookCategory[] = ['Comic Books', 'Harry Potter', 'Novels', 'Other'];
